import type { Metadata } from 'next'
import { Inter, Mochiy_Pop_One } from 'next/font/google'
import './globals.css'
import { cnMerge } from '../styles/cnMerge'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })
const mochiyPopOne = Mochiy_Pop_One({
  weight: '400',
  variable: '--font-header',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cnMerge(
          `min-h-screen bg-background font-sans antialiased ${inter.variable} ${mochiyPopOne.variable}`,
        )}
      >
        {children}
      </body>
    </html>
  )
}

export default RootLayout
